# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - script: mkdir -p ~/.local/bin
    displayName: 'Create local bin folder'

  - script: |
      echo ##vso[task.prependpath]%AGENT_BUILDDIRECTORY%\.tmp\node_modules\.bin
      echo $(PATH)

  - script: curl -sSL https://get.haskellstack.org/ | sh
    displayName: 'Setting up Stack'

  - script: make hie-8.4.4
    displayName: 'Build HIR for GHC 8.4.4'

