# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: linux
    image: quay.io/haskell_works/ghc-8.4.4

jobs:
  - job:
    displayName: First Job
    container: linux
    steps:
    - script: cabal new-update
      displayName: 'Updating Hackage indices'
    
    - script: cabal new-build
      displayName: 'Build HIE'

